### PR TITLE
Use keyring to store credentials

### LINKED ISSUE #6: Cache credentials so they don't need to be input every run
Cache credentials so they don't need to be input every time.

This can either be the password (encrypted, not plaintext) or http session cookie. I'm not familiar with how cookies TTL work, although it might be enough if the cookie can persist for a few days.

### PR DESCRIPTION
**Pull request by ipwnponies**
Well this was surprisingly easy. Fixes #6
This doesn't completely "cache" the credentials yet. I'm going to read the user from a config file.

### CODE REVIEW

**Review by edmundmok — APPROVED** [review]
Nice! Was going to look into this, but looks like its already done easily. Only tested it on MacOS though. 

One possible issue might be trying to update to a new password / resetting password in case of input error. We'll need a way to reset the stored password.

**Review by edmundmok — CHANGES_REQUESTED** [review]
Actually now that I think about this, if an attacker knows the user's email (or the email is stored in some config file), wouldn't it be easy to read from the keyring? Seems to be effectively storing the password in plaintext. I'm not sure if there's any foolproof way of storing credentials locally.

**Comment by edmundmok** [comment]
Would it be better to just store the cookie in the keyring, and if the cookie has expired, request relogin?

**Comment by ipwnponies** [comment]
I believe the system keyring to be the "not-rolling-your-own-crypto" approach that does exactly what we need (store a password for later retrieval). The keyring is instanced per user (i think this might be your misunderstanding). For an attacker to retrieve the plaintext password, they need to either:
* Have password to user's account, allowing them to login and unlock keyring
* Get a hold of system keyring datastore on disk (trivial), then break the publlc-private key encryption (or however the appropriate backend is implemented)

We could store the cookie instead if it's trivial to request fresh cookie without further user input for credentials (can you confirm hwo this works?).

Otherwise we need to deal with when to prompt the user:
* How do we notify the user? They might have set up scheduler long time ago, on remote machine.
* When do we prompt because it would be bad experience to request upon scheduled task run (17:00), which means meals aren't reserved as expected.

Which seems inelegant. Whatever the solution is, it shoudl be a hands-off solution.

**Comment by edmundmok** [comment]
The situation I had in mind may be a bit far-fetched, where a user executes a malicious program that accesses the keyring details according to our code -- in that case the program would be able to retrieve the necessary credentials, right?

This feature is definitely still useful, but I think it would also be useful to have an opt-out for users who don't want their credentials stored locally. In that case, we could either fallback to caching the cookie (~~doesn't matter even if it expires~~, at least it saves some keystrokes), or requesting credentials again.

EDIT: Actually it does matter if the cookie expires, in terms of user experience like what you mentioned above. Definitely need to check if the cookie does refresh. Even so, its possible the program doesn't manage to refresh in time, e.g. laptop sleeps > 24 hrs. An opt-out for users who want to just schedule 1 day at a time (few hours in advance) would still be useful though.

**Comment by ipwnponies** [comment]
If the user executes a malicious program, everything in the keyring is compromised. Not only this entry but all credentials. i.e. Safari stores "save my password" entries in OSX keychain, so if they save password for online banking.

This change doesn't grant any more access to the keyring than before. The user shares the same level of risk as other secrets as before by storing in the keyring.

Edit: [source regarding security](https://stackoverflow.com/a/14682785) that I found while investigating `python-keyring`

**Comment by edmundmok** [comment]
I think in Safari it might be harder to extract credentials since the "service name" and "username" are hidden, whereas here the code is open source and the "key" to the password is more easily available. 
Can we just make this opt-in instead, and only store email by default for now as per #18, but if users are confident in managing any potential risks they can opt-in to have their password stored locally.

**Comment by ipwnponies** [comment]
I agree, let's make this opt-in (via cli option or subcommand to set it up). Not everyone will want to store credentials and it's not necessary to run this script, i.e, a user only wants to run this adhoc and are fine entering their creds each time. We can follow-up on how to handle expired cookies for an scheduled task in separate feature request. I'll rework this to put it behind a feature toggle, one that will be hooked up through `click` option in future.

**Note**: I already wrote the below so I figured I might as well publish it, if only for academic discussion and learning. It shouldn't affect what to do for next to fix review.

"Service name" and "username" are not secrets and it's not necessary to rely on "security through obscurity". Some backends allow [iterating through all credentials](https://github.com/jaraco/keyring/issues/151#issuecomment-75765809) and the author of `keyring` has no qualms endorsing this solution. The keyring is a data store of credentials, if you are able to access it by logging in (access to OS user creds), you'll have access to everything. An attacker cannot break into the keyring for a targeted single credential, hiding or revealing this doesn't help them. Unless I'm missing something here.

**Comment by edmundmok** [comment]
So basically once the attacker has access to a keychain session (in the example I described, assuming the user had a keychain session running prior to running the attacker's program), the program essentially has access to the entire data store? Interesting to know.

**Comment by ipwnponies** [comment]
The last few paragrpahs in the linked [source](https://stackoverflow.com/questions/14636290/secure-credential-storage-in-python/14682785#14682785) summarizes this:

> Ultimately, though, if the hacker has control over the computer, there is no privacy on the computer at all. Theoretical worst-case is that your program is running in a VM, and the hacker has complete access to all memory on the computer, including the BIOS and graphics card, and can step your application though authentication to discover its secrets.

> Given no absolute privacy, the rest is just obfuscation, and the level of protection is simply how hard it is obfuscated vs. how much a skilled hacker wants the information. And we all know how that ends, even for custom hardware and billion-dollar products.

> [Regarding using python keyring,] While this will quite securely manage the key with respect to other applications, all Python applications share access to the tokens. This is not in the slightest bit secure to the type of attack you are worried about.

If an attacker phished a user into running a rogue python script, they will have access to all keyring data. But in this case, the attacker is already in a good position to do other nefarious deeds (read files, install other scripts, etc.). re: "given no absolute privacy"

It's not feasible nor practical (relative to this script) to design for 100% security. Instead, we trade off security for convenience and get lumped into same risk pool as other credentials stored in keyring.

**Comment by ipwnponies** [comment]
The changes are such that it's disabled by default. It looks kinda dumb atm because we need cli options to handle feature toggle in more elegant way. But works the same as before and can be transparently opt-in to keyring.

**Review by edmundmok — APPROVED** [review]

**Comment by edmundmok** [comment]
LGTM, feel free to merge after conflicts are resolved!

**Pull request merged**
